### ISSUE TITLE
DPAD doesn't register WASD

### ISSUE THREAD

**Issue by ragasubekti** [Xtr126/XtMapper#5] opened 2023-02-09 14:34 UTC
On the event logs, it was pretty clear that it's able to read WASD key, but it doesn't seem to send any input into the game. Using arrow keys is working fine.

**Comment by Xtr126** [comment] 2023-02-11 08:15
I can't seem to be able to reproduce this issue on my end with Bliss OS 15.8.3 and app version v1.3
Can you please provide more info, what were the exact keycodes you saw. `KEY_W`, `KEY_A` or something else.
And does it happen only in Genshin Impact ?
Thanks

**Comment by ragasubekti** [comment] 2023-02-11 11:33
It seems like it doesn't work at all on all games, the keycodes that i saw when pressing the key on app is `KEY_W`,`KEY_A`,`KEY_D`,`KEY_S`. The system info is similiar to yours running `BlissOS_15.8.3_gapps` and version 1.3 of the XtMapper 


![JskFw9r - Imgur](https://user-images.githubusercontent.com/20393246/218255766-4609e5c2-5213-4428-af05-c1e101ed8138.png)

**Comment by Xtr126** [comment] 2023-02-12 03:28
> It seems like it doesn't work at all on all games, the keycodes that i saw when pressing the key on app is `KEY_W`,`KEY_A`,`KEY_D`,`KEY_S`. The system info is similiar to yours running `BlissOS_15.8.3_gapps` and version 1.3 of the XtMapper

Looks like it should be fine. I'll look into it and see what I can do before next release.
In the meantime you could check /data/data/xtr.keymapper/files/config.* and see if there is a line like `WASD_DPAD 504.24026 447.9666 100.0 604.24023 547.9666`, if not should add it from keymap editor.

**Comment by ragasubekti** [comment] 2023-02-12 18:07
Seems like that's the issue, it register the dpad as ULDR_DPAD only, and not both

**Comment by Xtr126** [comment] 2023-02-16 05:27
Closing for now as this issue should be fixed now as of https://github.com/Xtr126/XtMapper/commit/f91a1b9799d035fbf66453e853da072e7b13d612

**Closed as completed by Xtr126** 2023-02-16 05:27 UTC
