### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Sandesh2007** [Xtr126/XtMapper#89] opened 2024-04-25 01:40 UTC
when i try to activate the app using the command given in the app {
sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh }
it gives a error {
 sh: /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh: No such file or directory }
i even tried to use with sizuku but not working. it only says connecting to server 

os:zorinos 17
waydroid

**Comment by Xtr126** [comment] 2024-04-25 02:11
> when i try to activate the app using the command given in the app { sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh } it gives a error { sh: /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh: No such file or directory } i even tried to use with sizuku but not working. it only says connecting to server
> 
> os:zorinos 17 waydroid

Duplicate of https://github.com/Xtr126/wayland-getevent/issues/5
Unrooting the waydroid container if you have it rooted or the chmod 777 hack should help https://github.com/casualsnek/waydroid_script?tab=readme-ov-file#granting-full-permission-for-apps-data-hack

**Closed as completed** 2024-04-25 14:31 UTC
