### ISSUE TITLE
./client | sudo waydroid shell -- sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh --wayland-client

### ISSUE THREAD

**Issue by orcbolg3612** [Xtr126/XtMapper#93] opened 2024-05-07 17:56 UTC
I installed XtMapper app then using wayland client from yours but it isn't work because there's no XtMapper files from /Android/data ????
I am using fedora 40 with wayland.

**Comment by Xtr126** [comment] 2024-05-09 03:57
Duplicate of https://github.com/Xtr126/wayland-getevent/issues/5.
As stated in the README you have to unroot the waydroid container or not grant root access to the app.

**Closed as not planned** 2024-05-16 08:35 UTC
